name: Deploy to VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SOPS
        run: |
          SOPS_VERSION=3.10.2
          curl -L https://github.com/opensops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64 -o sops
          chmod +x sops
          sudo mv sops /usr/local/bin/sops


      - name: Copy encrypted env file to VPS
        run: scp -o StrictHostKeyChecking=no secrets.env.enc ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/docker/lf-prj/

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            set -e
            cd /home/${{ secrets.VPS_USER }}/docker/lf-prj &&
            if [ -f .env ]; then
              cp .env .env.backup.\$(date +%Y%m%d_%H%M%S)
            fi &&
            export SOPS_AGE_KEY_FILE=/home/${{ secrets.VPS_USER }}/.config/sops/age/keys.txt &&
            sops -d secrets.env.enc > .env &&
            docker compose down &&
            docker compose up -d --build
          "
